### PR TITLE
fix: function invalid/incomplete closure serialize poison pill

### LINKED ISSUE #223: Error Code page Gen missing from build path
After PR #221, the error code page changed, but was not included in the self-mutation.

Likely due to prettier.

* [ ] Error code page is always up to date in PR (either self-mutation or commit hook).

### LINKED ISSUE #227: Multiple calls to app.synth() breaks Function serialization
If the CDK `app.synth()` is called twice, such as having `autoSynth:true` and then manually calling it, the Function closure serializer fails to re-bind the function body, resulting in the dummy code being deployed.

See https://github.com/functionless/functionless/issues/128#issuecomment-1153030191

### PR DESCRIPTION
**Pull request by thantos**
Resolves #227, Closes #223 

* If the CDK app uses `Function`s and does not await the Function Closure Serialize functions (see #128), the synthesis will fail with validation errors.
* Removed the error code page from the repo, it will be auto generated when the website is generated.
  * Originally we wanted to add this generation to the pre-commit hook. However, the generation of this file requires the typedocs to be generated and that requires the while site to build. This is a slow process we should not wait on during pre-commit. 
  * Now the error code page will be generated just like the updated typedocs, during the netlfiy build. The Netlify output can be used to review the changes.

### CODE REVIEW

File: src/function.ts [hunk 1]
```diff
@@ -608,6 +611,19 @@ export class Function<in Payload, Out, OutPayload extends Payload = Payload> ext
...
+        // In order for the synthesis to complete successfully 
+        // 1. Use autoSynth `new App({ autoSynth: true })` or `new App()` with the CDK Cli (`cdk synth`)
+        // 2. Use `await asyncSynth(app)` exported from Functionless in place of `app.synth()`
+        // 3. Manually await on the closure serializer promises `await Promise.all(Function.promises)`
+        // https://github.com/functionless/functionless/issues/128
+        _resource.node.addValidation({
+          validate: () => this.resource.node.metadata.find(m => m.type === FUNCTION_CLOSURE_FLAG) 
+            ? [] 
+            : [formatErrorMessage(ErrorCodes.Function_Closure_Serialization_Incomplete)]
+        });
```
Comment (sam-goodwin) [inline src/function.ts:625]: When do these validations run?

Comment (thantos) [reply src/function.ts:625]: Immediately before synth, after app.synth is called.

I'm pretty excited about the find. Feel like there will be more uses for this...

The cool thing is that the validations do not short circuit, cdk shows all errors for all constructs. 

Which means we could do something like error on an assertion about least privilege at the last moment. 

() => table.neverWrite() // fails during synth if the lambda role contains write

Comment (sam-goodwin) [reply src/function.ts:625]: I was wondering how it plays with the promises? Wouldn't the validate have a chance of running before the promises have completed?

Comment (thantos) [reply src/function.ts:625]: It should run as part of synth, so if the promises have been awaited before synth, the validation will pass and if the promises have not been allowed to complete, they will fail.

There is a chance that the validation succeeds because the promises happen to complete before synth is called, in which case the state is correct.

1. serialize 
2. synth
   3. validate (fail if 1 has not completed - only possible by luck)

1. serialize
2. await
3. synth
  4. validate (pass)
  5. output

Comment (sam-goodwin) [reply src/function.ts:625]: What happens when using auto synth? The promises won't be awaited

Comment (thantos) [reply src/function.ts]: The node process waits for the promises before executing synth. I tested this with the cli. 

`cdk synth` works as long as `app.synth()` isn't called manually.

**Review by sam-goodwin — APPROVED** [review]
