### PR TITLE
fix: add _brand to ITable and BaseTable to fix type inference of$ AWS.DynamoDB.Table

### LINKED ISSUE #253: A narrow Table<T, PK, RK> is not assignable to ITable<any, any, any>
```ts
interface Item {
  id: string;
  name: string;
}
let table = new Table<Item, "id">(stack, "table", {
  partitionKey: {
    name: "id",
    type: aws_dynamodb.AttributeType.NUMBER,
  },
});
declare let t: ITable<any, any, any>;

// @ts-expect-error
t = table;
```

Error:
```
error TS2322: Type 'Table<Item, "id", undefined>' is not assignable to type 'ITable<any, any, any>'.
  Types of property 'getItem' are incompatible.
    Type 'DynamoIntegrationCall<"getItem", DynamoIntegrationCall<"getItem", <Key extends { id: S<string>; }>(input: { key: Key; consistentRead?: boolean | undefined; }) => Extract<Item, AttributeKeyToObject<Key>>>>' is not assignable to type 'DynamoIntegrationCall<"getItem", <Key extends { [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<any> | L<{ [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<...> | L<...> | M<...> | undefined; }> | M<...> | undefined; }>(input: { ...; }) => Extract<...>>'.
      Type 'DynamoIntegrationCall<"getItem", DynamoIntegrationCall<"getItem", <Key extends { id: S<string>; }>(input: { key: Key; consistentRead?: boolean | undefined; }) => Extract<Item, AttributeKeyToObject<Key>>>>' is not assignable to type '{ kind: "Table.getItem"; __functionBrand: <Key extends { [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<any> | L<{ [x: string]: NULL | N<number> | B | BOOL<any> | ... 4 more ... | undefined; }> | M<...> | undefined; }>(input: { ...; }) => Extract<...>; }'.
        Types of property '__functionBrand' are incompatible.
          Type '{ kind: "Table.getItem"; __functionBrand: <Key extends { id: S<string>; }>(input: { key: Key; consistentRead?: boolean | undefined; }) => Extract<Item, AttributeKeyToObject<Key>>; } & (<Key extends { ...; }>(input: { ...; }) => Extract<...>)' is not assignable to type '<Key extends { [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<any> | L<{ [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<any> | L<...> | M<...> | undefined; }> | M<...> | undefined; }>(input: { ...; }) => Extract<...>'.
            Types of parameters 'input' and 'input' are incompatible.
              Type '{ key: Key; consistentRead?: boolean | undefined; }' is not assignable to type '{ key: { id: S<string>; }; consistentRead?: boolean | undefined; }'.
                Types of property 'key' are incompatible.
                  Type 'Key' is not assignable to type '{ id: S<string>; }'.
                    Property 'id' is missing in type '{ [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<any> | L<{ [x: string]: NULL | N<number> | B | BOOL<any> | S<any> | N<any> | L<...> | M<...> | undefined; }> | M<...> | undefined; }' but required in type '{ id: S<string>; }'.

136 t = table;
```

### PR DESCRIPTION
**Pull request by sam-goodwin**
Fixes #253 

The `Table` and `ITable` types had a problem where type inference worked for `ITable` but not for `Table`. 

Also, `ITable<any, any, any>` was properly short-circuiting types.

Adding a `_brand` property to both `ITable` and `BaseTable` containing the type parameters fixed the error. I believe this is because it makes the type information readily accessible to the compiler which is maybe struggling to infer them out of the `getItem` calls.

### CODE REVIEW

File: src/table.ts [hunk 1]
```diff
@@ -59,7 +59,11 @@ export interface TableProps<
     : undefined;
 }
 
-export type AnyTable = ITable<object, keyof object, keyof object | undefined>;
+export type AnyTable = ITable<
+  Record<string | number | symbol, any>,
+  string | number | symbol,
+  string | number | symbol | undefined
```
Comment (thantos) [inline src/table.ts:65]: is there a valid case with `number | symbol`?

Comment (thantos) [reply src/table.ts:65]: I was trying to `Exclude<keyof object, number | symbol>` instead

Comment (sam-goodwin) [reply src/table.ts:65]: For `AnyTable`, i think better to leave it open so that `any` will work. 

image

Comment (sam-goodwin) [reply src/table.ts:65]: Hmm nevermind, doesn't seem to affect anything. Will do this

Comment (sam-goodwin) [reply src/table.ts:65]: `keyof object` doing weird things for me ...
image

**Review by thantos — APPROVED** [review]
