### PR TITLE
fix: equals and in operators for app sync

### LINKED ISSUE #230: Cryptic VTL error message
I'm getting the following error in AppSync Query response:

```json
{
  "data": {
    "account": null
  },
  "errors": [
    {
      "path": [
        "account"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Encountered \"in\" at velocity[line 7, column 30]\nWas expecting one of:\n    <RPAREN> ...\n    \"-\" ...\n    \"+\" ...\n    \"*\" ...\n    \"/\" ...\n    \"%\" ...\n    <LOGICAL_AND> ...\n    <LOGICAL_OR> ...\n    <LOGICAL_LT> ...\n    <LOGICAL_LE> ...\n    <LOGICAL_GT> ...\n    <LOGICAL_GE> ...\n    <LOGICAL_EQUALS> ...\n    <LOGICAL_NOT_EQUALS> ...\n    "
    }
  ]
}
```

Here is the resolver I hooked up to this:

```ts
const resolver = new AppsyncResolver(($context) => {
      const identity = $context.identity;
      let accountId = 'barfoo';
      let apiKey = 'foobar';
      if (identity && 'resolverContext' in identity) {
        accountId = identity.resolverContext.accountId;
        apiKey = identity.resolverContext.apiKey;
      }

      console.log('USER: accountId: ', accountId);
      console.log('USER: apiKey: ', apiKey);

      if (!accountId && !apiKey)
        $util.error('AccountId and ApiKey must be non-empty');

      return table.getItem({
        key: {
          PK: { S: accountId },
          SK: { S: apiKey },
        },
      });
    });
```

And this is the CloudWatch log entry:

```json
{
    "logType": "RequestMapping",
    "path": [
        "account"
    ],
    "fieldName": "account",
    "resolverArn": "arn:aws:appsync:us-east-1:435193165691:apis/wc5qtkxi6bhndnb6fqhb3kah3m/types/Query/resolvers/account",
    "functionName": "Table_getItem",
    "requestId": "3450dde7-3cb7-4aeb-bfa9-a4e2ba7b5cb8",
    "context": {
        "arguments": {},
        "prev": {
            "result": {}
        },
        "stash": {},
        "outErrors": []
    },
    "fieldInError": true,
    "errors": [
        "Unable to transform the request mapping template."
    ],
    "parentType": "Query",
    "graphQLAPIId": "wc5qtkxi6bhndnb6fqhb3kah3m",
    "functionArn": "arn:aws:appsync:us-east-1:435193165691:apis/wc5qtkxi6bhndnb6fqhb3kah3m/functions/llq46pckvngsndzdhq5xyeqrre"
}
```

### PR DESCRIPTION
**Pull request by thantos**
Fixes #230

### CODE REVIEW

File: src/vtl.ts [hunk 1]
```diff
@@ -188,6 +188,14 @@ export class VTL {
       case "BinaryExpr":
         // VTL fails to evaluate binary expressions inside an object put e.g. $obj.put('x', 1 + 1)
         // a workaround is to use a temp variable.
+        if (node.op === "in") {
+          // !! right[left]
+          return this.var(
+            `!!${this.eval(node.right)}[${this.eval(node.left)}]`
```
Comment (sam-goodwin) [inline src/vtl.ts:194]: VTL has the `!!` operator?

File: test/vtl.test.ts [hunk 2]
```diff
@@ -369,3 +369,148 @@ test("BinaryExpr and UnaryExpr are evaluated to temporary variables", () =>
...
+          context: { arguments: { key: "hello" }, source: {} },
+          match: { out: "ohh hi" },
+        },
+        {
+          index: 1,
+          context: { arguments: { key: "giddyup" }, source: {} },
+          match: { out: "wot" },
+        },
+      ],
+    }
```
Comment (sam-goodwin) [inline test/vtl.test.ts:450]: This part of the test obfuscates imo. It's not obvious what it means.

**Review by sam-goodwin — CHANGES_REQUESTED** [review]

File: src/vtl.ts (hunk 1 above)
Comment (thantos) [reply src/vtl.ts:194]: not not

Though now I am concerned that this would not work with a falsely value...

Any idea how to prove existence?

Comment (sam-goodwin) [reply src/vtl.ts:194]: Use HashMap .has

Comment (thantos) [reply src/vtl.ts:194]: `has` returns false.

Comment (thantos) [reply src/vtl.ts]: `.containsKey`

https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#containsKey-java.lang.Object-

and `arr.length >= [left]` for array.

File: src/expression.ts [hunk 3]
```diff
@@ -279,20 +279,15 @@ export class ConditionExpr extends BaseExpr<"ConditionExpr"> {
 
 export const isBinaryExpr = typeGuard("BinaryExpr");
 
+export type ValueComparisonBinaryOp = "==" | "!=" | "<" | "<=" | ">" | ">=";
+export type MathBinaryOp = "/" | "*" | "+" | "-";
+export type LogicBinaryOp = "&&" | "||";
```
Comment (sam-goodwin) [inline src/expression.ts:284]: nit: `ComparatorOp`

File: src/vtl.ts [hunk 4]
```diff
@@ -186,6 +195,39 @@ export class VTL {
...
+            new BinaryExpr(
+              new PropAccessExpr(node.right, "length"),
+              ">=",
+              node.left
+            ),
+            new CallExpr(new PropAccessExpr(node.right, "containsKey"), [
+              new Argument(node.left),
+            ])
+          );
+          condition.setParent(node);
```
Comment (sam-goodwin) [inline src/vtl.ts:225]: Should we do this re-write prior to interpreting with a `visitEachChild` transformer?

**Review by sam-goodwin — CHANGES_REQUESTED** [review]

File: src/vtl.ts (hunk 4 above)
Comment (thantos) [reply src/vtl.ts:225]: 1. Wouldn't the logic be essentially the same without the extra pass?
2. Could I do that when I refactor app sync later?

File: src/vtl.ts [hunk 5]
```diff
@@ -186,6 +195,39 @@ export class VTL {
...
+           *    right.containsKey(left);
+           */
+          const condition = new ConditionExpr(
+            new BinaryExpr(
+              new PropAccessExpr(
+                new PropAccessExpr(node.right, "class"),
+                "name"
+              ),
+              "==",
+              new StringLiteralExpr("ArrayList")
```
[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts:214]: yes :-) I did test this on app sync, but of course there may be other surprises

```
  | 2022-06-12T23:21:26.704-05:00 | c394598f-1d78-441c-b082-f9e552a4a008 INFO - java.util.LinkedHashMap
-- | -- | --
  | 2022-06-12T23:21:26.704-05:00 | c394598f-1d78-441c-b082-f9e552a4a008 INFO - java.util.ArrayList
```

[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts:214]: ohh shit, `java.util.ArrayList` haha...

[the remark this answers is not in the document]
Comment (sam-goodwin) [reply src/vtl.ts]: Check the class of an object on $input. It has some weird custom map class

[the remark this answers is not in the document]
Comment (sam-goodwin) [reply src/vtl.ts]: Curious if there is a custom list class for when it's immutable

File: src/vtl.ts (hunk 4 above)
Comment (sam-goodwin) [reply src/vtl.ts:225]: 1. Yeah but you wouldn't have to `setParent` yourself.
2. sure, no biggie, but it would be pretty easy to do
```ts
constructor() {
  const transformedAst = visitEachChild(functionDecl, function normalizeAST(node) {
    if (isBinaryOp(node) && .. ) {
       // same code you already have, minus setParent
    }
  });
}
```

File: src/vtl.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts]:
```ts
2022-06-13T14:20:32.949-05:00 | c849ccde-0e70-4b50-bc0f-253681d23648 INFO - args: java.util.LinkedHashMap
-- | --
  | 2022-06-13T14:20:32.949-05:00 | c849ccde-0e70-4b50-bc0f-253681d23648 INFO - context: com.amazonaws.deepdish.transform.model.MappingTemplateContext
  | 2022-06-13T14:20:32.949-05:00 | c849ccde-0e70-4b50-bc0f-253681d23648 INFO - request: com.amazonaws.deepdish.common.DeepdishRequestObject
```

[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts]: DeepdishRequestObject

[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts]: hmmm

$context.identity.sourceId

`[Ljava.lang.String;`

Well shit.

File: src/vtl.ts (hunk 1 above)
Comment (thantos) [reply src/vtl.ts]: thats how I am recreating 

`index in array` 
`1 in [1,2] => true`
`2 in [1,2] => false`

in typescript

File: src/vtl.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts]: Options:

1. check for `.class.name.startsWith('[L') || .class.name.contains('ArrayList')`
2. drop support for array lists and just let it fail when someone tries `arr.containsKey()` will just return null

[the remark this answers is not in the document]
Comment (sam-goodwin) [reply src/vtl.ts]: Any drawbacks with the startsWith strategy?

[the remark this answers is not in the document]
Comment (thantos) [reply src/vtl.ts]: We may find more patterns in the future, but I think its OK. using number in array is not a common use case.

**Review by sam-goodwin — APPROVED** [review]

File: src/vtl.ts (hunk 1 above)
Comment (sam-goodwin) [reply src/vtl.ts]: I don't understand.

Comment (thantos) [reply src/vtl.ts]: `In` for array checks for the existence of indices.
