### PR TITLE
fix: lambda invoke from step function, start step function localstack tests

### LINKED ISSUE #307: Step functions lambda integration doesn't result valid result
Testing against localstack, may be their issue too. We'll see.

```
    Expected: "hello world"
    Received: "$.Payload"
```

The result is the contents of the `ResultSelector` field.

According to AWS, the result selector should be a object with fields.

> Use the ResultSelector field to manipulate a state's result before ResultPath is applied. The ResultSelector field lets you create a collection of key value pairs, where the values are static or selected from the state's result. The output of ResultSelector replaces the state's result and is passed to ResultPath.

Our definition:

```ts
exports[` 2`] = `
Object {
  "StartAt": "return await func()",
  "States": Object {
    "return await func()": Object {
      "End": true,
      "Parameters": Object {
        "FunctionName": "\${Token[TOKEN.242]}",
        "Payload": undefined,
      },
      "Resource": "arn:aws:states:::lambda:invoke",
      "ResultPath": "$",
      "ResultSelector": "$.Payload",
      "Type": "Task",
    },
  },
}
`;
```

### PR DESCRIPTION
**Pull request by thantos**
Fixes #307 

* Add some localstack tests for step functions (Standard only, [Express is not supported by localstack](https://github.com/localstack/localstack/issues/5258))
   * No response from localstack in 6mo, unlikely to see this.
* Lambda integration uses the direct resource reference which accepts the payload directly and returns the response
  * Analyze the parameter to determine how to build the task.
* Fix `$AWS.Lambda.Invoke` which was using the wrong parameter name.

### CODE REVIEW

**Comment by sam-goodwin** [comment]
> fix: fix

File: src/aws.ts [hunk 1]
```diff
@@ -422,18 +423,18 @@ export namespace $AWS {
...
           throw new Error(
-            "property 'FunctionName' must reference a functionless.Function"
+            "property 'Function' must reference a functionless.Function"
           );
         }
         const functionRef = functionName.ref();
         if (!isFunction(functionRef)) {
           throw new Error(
-            "property 'FunctionName' must reference a functionless.Function"
+            "property 'Function' must reference a functionless.Function"
```
Comment (sam-goodwin) [inline src/aws.ts:437]: Did we somehow miss these or is this a merge problem?

File: src/function.ts [hunk 2]
```diff
@@ -383,15 +387,30 @@ abstract class FunctionBase<in Payload, Out>
...
+      } else if (isStringLiteralExpr(payloadArg)) {
+        return {
+          Parameters: payloadArg.value,
+        };
+      } else {
+        return {
+          Parameters: ASL.toJson(payloadArg),
+        };
+      }
+    })();
```
Comment (sam-goodwin) [inline src/function.ts:409]: Use ternary instead of an instantly called function closure?

File: test/__snapshots__/step-function.localstack.test.ts.snap [hunk 3]
```diff
@@ -0,0 +1,386 @@
+// Jest Snapshot v1, https://goo.gl/fbAQLP
+
+exports[` 1`] = `
```
Comment (sam-goodwin) [inline test/__snapshots__/step-function.localstack.test.ts.snap:3]: Is this missing a description?

File: test/__snapshots__/step-function.test.ts.snap [hunk 4]
```diff
@@ -11,13 +11,9 @@ Object {
         "States": Object {
           "return task(item)": Object {
             "End": true,
-            "Parameters": Object {
-              "FunctionName": "__REPLACED_TOKEN",
-              "Payload.$": "$.item",
-            },
-            "Resource": "arn:aws:states:::lambda:invoke",
```
Comment (sam-goodwin) [inline test/__snapshots__/step-function.test.ts.snap:18]: Ah, was I calling the AWS SDK integration?

File: test/function.localstack.test.ts [hunk 5]
```diff
@@ -131,7 +100,7 @@ localstackTestSuite("functionStack", (testResource, _stack, _app) => {
   // eslint-disable-next-line no-only-tests/no-only-tests
   test.only = _testFunc(testResource.only);
 
-  test(
+  test.only(
```
Comment (sam-goodwin) [inline test/function.localstack.test.ts:103]: oops?

File: src/function.ts (hunk 2 above)
Comment (thantos) [reply src/function.ts:409]: I can, yeah. This will likely get much more complex and at one point I was trying to generate multiple states. Right now I guess it would be a mostly readable ternary.

File: test/__snapshots__/step-function.localstack.test.ts.snap (hunk 3 above)
Comment (thantos) [reply test/__snapshots__/step-function.localstack.test.ts.snap]: The self-mutation should remove these. I was comparing the snapshots outside of the tests and jest didn't like that (even though I was giving it a name).

File: test/__snapshots__/step-function.test.ts.snap (hunk 4 above)
Comment (thantos) [reply test/__snapshots__/step-function.test.ts.snap:18]: No, the "optimized", but also returning the whole response wrapper when we didn't need it. The largest issue was the `ResultPath` being a string and not an object. It turned out easier to correctly format the input than to manipulate the response.

File: test/function.localstack.test.ts (hunk 5 above)
Comment (thantos) [reply test/function.localstack.test.ts]: Why didn't that get removed? strange... thanks for the catch.

File: src/aws.ts (hunk 1 above)
Comment (thantos) [reply src/aws.ts:437]: Not sure! This is why tests that actually execute the code is important.

Comment (thantos) [reply src/aws.ts:437]: I think it was missed, the last change on that line was 2 months ago.

**Review by sam-goodwin — APPROVED** [review]

File: test/step-function.localstack.test.ts [hunk 6]
```diff
@@ -0,0 +1,219 @@
...
+        const [funcRes, outputs] =
+          res instanceof StepFunction ? [res, {}] : [res.sfn, res.outputs];
+        return {
+          outputs: {
+            function: funcRes.resource.stateMachineArn,
+            ...outputs,
+          },
+          extra: {
+            definition: JSON.stringify(funcRes.definition),
+          },
```
[the remark this answers is not in the document]
Comment (thantos) [reply test/step-function.localstack.test.ts:49]: The tokens in output are resolved, which create quite a few patterns of random values. tokens are much easier to find and we don't need the resolved tokens in the snapshot.

[the remark this answers is not in the document]
Comment (thantos) [reply test/step-function.localstack.test.ts:49]: Function name, arns, etc where creating randomized snapshots.

**Review by sam-goodwin — APPROVED** [review]
